name: weather-api

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    build: .
    environment:
      REDIS_HOST: redis
      WEATHER_API_KEY: ${WEATHER_API_KEY}
    ports:
      - "8080:8080"